import type { PosePresetGroupKey, PosePresetKey } from '../figure/posePresets'

/**
 * Rótulos (chaves de i18n) das poses de fábrica e dos seus grupos. Moravam
 * dentro do `PropertiesPanel.tsx`; viraram módulo próprio quando o módulo de
 * poses ganhou as poses de partida na aba Boneco (item 52) — o combo de lá usa
 * exatamente as mesmas chaves, e duplicar o mapa seria uma cópia a divergir.
 *
 * As chaves continuam sob `panels.properties.*`: são as mesmas strings, e
 * reagrupá-las no JSON quebraria tradução por nada.
 */

export const POSE_PRESET_LABEL_KEYS: Record<PosePresetKey, string> = {
  standing: 'panels.properties.posePresetStanding',
  tpose: 'panels.properties.posePresetTPose',
  sitting: 'panels.properties.posePresetSitting',
  walking: 'panels.properties.posePresetWalking',
  running: 'panels.properties.posePresetRunning',
  lyingHandsBehindHead: 'panels.properties.posePresetLying',
  fetal: 'panels.properties.posePresetFetal',
  fighting: 'panels.properties.posePresetFighting',
  superman: 'panels.properties.posePresetSuperman',
  model: 'panels.properties.posePresetModel',
  punchGiving: 'panels.properties.posePresetPunchGiving',
  punchTaking: 'panels.properties.posePresetPunchTaking',
  kickGiving: 'panels.properties.posePresetKickGiving',
  kickTaking: 'panels.properties.posePresetKickTaking',
  chokeGiving: 'panels.properties.posePresetChokeGiving',
  chokeTaking: 'panels.properties.posePresetChokeTaking',
  apose: 'panels.properties.posePresetAPose',
  pointForward: 'panels.properties.posePresetPointForward',
  pointUp: 'panels.properties.posePresetPointUp',
  pointDown: 'panels.properties.posePresetPointDown',
  pointFar: 'panels.properties.posePresetPointFar',
  pointAtOther: 'panels.properties.posePresetPointAtOther',
  presenting: 'panels.properties.posePresetPresenting',
  pointSelf: 'panels.properties.posePresetPointSelf',
  thumbBack: 'panels.properties.posePresetThumbBack',
  squat: 'panels.properties.posePresetSquat',
  kneelingOneKnee: 'panels.properties.posePresetKneelingOneKnee',
  kneelingBoth: 'panels.properties.posePresetKneelingBoth',
  crossLegged: 'panels.properties.posePresetCrossLegged',
  allFours: 'panels.properties.posePresetAllFours',
  plank: 'panels.properties.posePresetPlank',
  pronePropped: 'panels.properties.posePresetPronePropped',
  sideLying: 'panels.properties.posePresetSideLying',
  touchToes: 'panels.properties.posePresetTouchToes',
  armsCrossed: 'panels.properties.posePresetArmsCrossed',
  handsOnHips: 'panels.properties.posePresetHandsOnHips',
  waving: 'panels.properties.posePresetWaving',
  celebrating: 'panels.properties.posePresetCelebrating',
  handOnChin: 'panels.properties.posePresetHandOnChin',
  headDown: 'panels.properties.posePresetHeadDown',
  startled: 'panels.properties.posePresetStartled',
  kpopFingerHeart: 'panels.properties.posePresetKpopFingerHeart',
  kpopBoxArms: 'panels.properties.posePresetKpopBoxArms',
  kpopPointDance: 'panels.properties.posePresetKpopPointDance',
  kpopShoulderWave: 'panels.properties.posePresetKpopShoulderWave',
  jumping: 'panels.properties.posePresetJumping',
  throwing: 'panels.properties.posePresetThrowing',
  kickingBall: 'panels.properties.posePresetKickingBall',
  carryingBox: 'panels.properties.posePresetCarryingBox',
  climbing: 'panels.properties.posePresetClimbing',
  stepUp: 'panels.properties.posePresetStepUp',
  balletPreparation: 'panels.properties.posePresetBalletPreparation',
  balletPirouette: 'panels.properties.posePresetBalletPirouette',
  handshake: 'panels.properties.posePresetHandshake',
  hug: 'panels.properties.posePresetHug',
  danceLead: 'panels.properties.posePresetDanceLead',
  danceFollow: 'panels.properties.posePresetDanceFollow',
  carryingPiggyback: 'panels.properties.posePresetCarryingPiggyback',
  carriedPiggyback: 'panels.properties.posePresetCarriedPiggyback',
  carryingCradle: 'panels.properties.posePresetCarryingCradle',
  carriedCradle: 'panels.properties.posePresetCarriedCradle',
  pullingUp: 'panels.properties.posePresetPullingUp',
  beingPulledUp: 'panels.properties.posePresetBeingPulledUp',
  pushGiving: 'panels.properties.posePresetPushGiving',
  pushTaking: 'panels.properties.posePresetPushTaking',
  kneeStrikeGiving: 'panels.properties.posePresetKneeStrikeGiving',
  kneeStrikeTaking: 'panels.properties.posePresetKneeStrikeTaking',
  armLockPushGiving: 'panels.properties.posePresetArmLockPushGiving',
  armLockPushTaking: 'panels.properties.posePresetArmLockPushTaking',
  armLockPullGiving: 'panels.properties.posePresetArmLockPullGiving',
  armLockPullTaking: 'panels.properties.posePresetArmLockPullTaking',
  clinch: 'panels.properties.posePresetClinch',
  meditating: 'panels.properties.posePresetMeditating',
  businessman: 'panels.properties.posePresetBusinessman',
  heroStance: 'panels.properties.posePresetHeroStance',
  lyingSpreadSupine: 'panels.properties.posePresetLyingSpreadSupine',
  lyingSpreadProne: 'panels.properties.posePresetLyingSpreadProne',
  sittingLegsForward: 'panels.properties.posePresetSittingLegsForward',
  sittingKneesBent: 'panels.properties.posePresetSittingKneesBent',
  rearChokeKneeling: 'panels.properties.posePresetRearChokeKneeling',
  rearChokeSeated: 'panels.properties.posePresetRearChokeSeated',
  groundChokeGiving: 'panels.properties.posePresetGroundChokeGiving',
  groundChokeTaking: 'panels.properties.posePresetGroundChokeTaking',
}

/** Descrição longa (tooltip) das poses cujo rótulo curto não se explica sozinho. */
export const POSE_PRESET_HINT_KEYS: Partial<Record<PosePresetKey, string>> = {
  lyingHandsBehindHead: 'panels.properties.posePresetLyingHint',
  fetal: 'panels.properties.posePresetFetalHint',
  fighting: 'panels.properties.posePresetFightingHint',
  superman: 'panels.properties.posePresetSupermanHint',
  model: 'panels.properties.posePresetModelHint',
  // As poses de luta vêm em par: a dica de cada uma diz com qual outra ela
  // se encaixa, senão não dá para saber que existe um par (DECISOES.md #35).
  punchGiving: 'panels.properties.posePresetPunchGivingHint',
  punchTaking: 'panels.properties.posePresetPunchTakingHint',
  kickGiving: 'panels.properties.posePresetKickGivingHint',
  kickTaking: 'panels.properties.posePresetKickTakingHint',
  chokeGiving: 'panels.properties.posePresetChokeGivingHint',
  chokeTaking: 'panels.properties.posePresetChokeTakingHint',
  apose: 'panels.properties.posePresetAPoseHint',
  pointForward: 'panels.properties.posePresetPointForwardHint',
  pointUp: 'panels.properties.posePresetPointUpHint',
  pointDown: 'panels.properties.posePresetPointDownHint',
  pointFar: 'panels.properties.posePresetPointFarHint',
  pointAtOther: 'panels.properties.posePresetPointAtOtherHint',
  presenting: 'panels.properties.posePresetPresentingHint',
  pointSelf: 'panels.properties.posePresetPointSelfHint',
  thumbBack: 'panels.properties.posePresetThumbBackHint',
  squat: 'panels.properties.posePresetSquatHint',
  kneelingOneKnee: 'panels.properties.posePresetKneelingOneKneeHint',
  kneelingBoth: 'panels.properties.posePresetKneelingBothHint',
  crossLegged: 'panels.properties.posePresetCrossLeggedHint',
  allFours: 'panels.properties.posePresetAllFoursHint',
  plank: 'panels.properties.posePresetPlankHint',
  pronePropped: 'panels.properties.posePresetProneProppedHint',
  sideLying: 'panels.properties.posePresetSideLyingHint',
  touchToes: 'panels.properties.posePresetTouchToesHint',
  armsCrossed: 'panels.properties.posePresetArmsCrossedHint',
  handsOnHips: 'panels.properties.posePresetHandsOnHipsHint',
  waving: 'panels.properties.posePresetWavingHint',
  celebrating: 'panels.properties.posePresetCelebratingHint',
  handOnChin: 'panels.properties.posePresetHandOnChinHint',
  headDown: 'panels.properties.posePresetHeadDownHint',
  startled: 'panels.properties.posePresetStartledHint',
  kpopFingerHeart: 'panels.properties.posePresetKpopFingerHeartHint',
  kpopBoxArms: 'panels.properties.posePresetKpopBoxArmsHint',
  kpopPointDance: 'panels.properties.posePresetKpopPointDanceHint',
  kpopShoulderWave: 'panels.properties.posePresetKpopShoulderWaveHint',
  jumping: 'panels.properties.posePresetJumpingHint',
  throwing: 'panels.properties.posePresetThrowingHint',
  kickingBall: 'panels.properties.posePresetKickingBallHint',
  carryingBox: 'panels.properties.posePresetCarryingBoxHint',
  climbing: 'panels.properties.posePresetClimbingHint',
  stepUp: 'panels.properties.posePresetStepUpHint',
  balletPreparation: 'panels.properties.posePresetBalletPreparationHint',
  balletPirouette: 'panels.properties.posePresetBalletPirouetteHint',
  // Nos pares, a dica é a única coisa que diz a DISTÂNCIA em que as duas
  // poses se encaixam — sem ela o encaixe resolvido numericamente não chega
  // ao usuário (DECISOES.md #37).
  handshake: 'panels.properties.posePresetHandshakeHint',
  hug: 'panels.properties.posePresetHugHint',
  danceLead: 'panels.properties.posePresetDanceLeadHint',
  danceFollow: 'panels.properties.posePresetDanceFollowHint',
  carryingPiggyback: 'panels.properties.posePresetCarryingPiggybackHint',
  carriedPiggyback: 'panels.properties.posePresetCarriedPiggybackHint',
  carryingCradle: 'panels.properties.posePresetCarryingCradleHint',
  carriedCradle: 'panels.properties.posePresetCarriedCradleHint',
  pullingUp: 'panels.properties.posePresetPullingUpHint',
  beingPulledUp: 'panels.properties.posePresetBeingPulledUpHint',
  pushGiving: 'panels.properties.posePresetPushGivingHint',
  pushTaking: 'panels.properties.posePresetPushTakingHint',
  kneeStrikeGiving: 'panels.properties.posePresetKneeStrikeGivingHint',
  kneeStrikeTaking: 'panels.properties.posePresetKneeStrikeTakingHint',
  armLockPushGiving: 'panels.properties.posePresetArmLockPushGivingHint',
  armLockPushTaking: 'panels.properties.posePresetArmLockPushTakingHint',
  armLockPullGiving: 'panels.properties.posePresetArmLockPullGivingHint',
  armLockPullTaking: 'panels.properties.posePresetArmLockPullTakingHint',
  clinch: 'panels.properties.posePresetClinchHint',
  meditating: 'panels.properties.posePresetMeditatingHint',
  businessman: 'panels.properties.posePresetBusinessmanHint',
  heroStance: 'panels.properties.posePresetHeroStanceHint',
  lyingSpreadSupine: 'panels.properties.posePresetLyingSpreadSupineHint',
  lyingSpreadProne: 'panels.properties.posePresetLyingSpreadProneHint',
  sittingLegsForward: 'panels.properties.posePresetSittingLegsForwardHint',
  sittingKneesBent: 'panels.properties.posePresetSittingKneesBentHint',
  rearChokeKneeling: 'panels.properties.posePresetRearChokeKneelingHint',
  rearChokeSeated: 'panels.properties.posePresetRearChokeSeatedHint',
  groundChokeGiving: 'panels.properties.posePresetGroundChokeGivingHint',
  groundChokeTaking: 'panels.properties.posePresetGroundChokeTakingHint',
}

export const POSE_PRESET_GROUP_LABEL_KEYS: Record<PosePresetGroupKey, string> = {
  reference: 'panels.properties.poseGroupReference',
  everyday: 'panels.properties.poseGroupEveryday',
  ground: 'panels.properties.poseGroupGround',
  pointing: 'panels.properties.poseGroupPointing',
  action: 'panels.properties.poseGroupAction',
  expressive: 'panels.properties.poseGroupExpressive',
  kpop: 'panels.properties.poseGroupKpop',
  pairs: 'panels.properties.poseGroupPairs',
  fight: 'panels.properties.poseGroupFight',
}
